// Package credentiallease is a task-bound client for a credential broker.
//
// The package does not issue provider credentials or hold broker administrator
// credentials. A workload presents a short-lived identity proof to a separate
// broker, asks for one credential bound to a task, audience, resource, actions,
// and delivery method, uses it only inside a callback, and asks the broker to
// revoke the lease when the callback returns. The broker's TTL remains the
// cleanup backstop if the client exits or revocation cannot complete.
//
// Credential bytes are kept private to Lease and can only be used by its Do
// method to send an HTTPS request to the target origin fixed at acquisition.
// Do also enforces the exact escaped resource path and allowed HTTP methods,
// rejects query strings, and disables redirects. Target services remain
// responsible for permissions encoded in request bodies. Applications must
// not log authenticated request headers or expose request details to
// model-visible tool output.
//
// TaskManager can exchange a workload's existing service credential for a
// short-lived proof and task ID generated by the broker. This conversion
// distinguishes broker-created task sessions inside the service, but the
// bootstrap credential still authenticates only that service principal; it
// does not independently attest a human, agent process, or individual task.
// TaskManager.WithTask scopes that identity to one callback and closes it on
// success, error, panic, or context cancellation. Closing a task prevents new
// lease requests and cancels in-flight callback contexts so revocation begins.
//
// This package defines the client side of the v1 broker protocol. A broker
// implementation must independently authenticate workload proofs, enforce
// task/audience/resource/action policy, audit issuance and revocation, and
// issue provider credentials with a bounded TTL.
//
// The optional Observer receives secret-free acquire, target-use, and revoke
// outcomes. Its use event includes only result, HTTP status, and duration.
package credentiallease
