// Package header defines canonical HTTP header name constants used
// across the fleet. Centralising them here prevents the silent auth
// bypass that one typo in a string literal can cause.
//
// Import:
//
//	import "github.com/baditaflorin/go-common/header"
//
//	r.Header.Set(header.APIKey, token)
//	user := r.Header.Get(header.AuthUser)
package header

// Inbound auth headers injected by the nginx gateway after a
// successful /verify call to the keystore. Downstream handlers
// trust these; they are never set by external clients because the
// gateway strips them on ingress.
const (
	// AuthUser is the verified user/service identity injected by the
	// gateway. Presence indicates the gateway already verified the key.
	AuthUser = header.AuthUser

	// AuthScope is the verified key scope injected by the gateway.
	// Services that need scope enforcement re-check via apikey.VerifyScope.
	AuthScope = header.AuthScope
)

// Request identification headers — threaded through the full
// request lifecycle for correlation in logs and traces.
const (
	// RequestID is generated by middleware.RequestID if absent,
	// then echoed in every response and stamped on every log line.
	RequestID = header.RequestID

	// FleetCaller is optionally set by mesh proxies to identify the
	// calling service when the User-Agent has been rewritten.
	FleetCaller = "X-Fleet-Caller"
)

// Client credential headers — set by callers, read by auth middleware.
const (
	// APIKey is the fleet API key header sent by service-to-service
	// callers and human-facing clients. Equivalent to Bearer in the
	// Authorization header; both are accepted.
	APIKey = header.APIKey
)

// Admin credential headers — used by apikey admin endpoints.
const (
	// AdminToken is the header used to authenticate admin operations
	// against the keystore (/issue, /revoke, /list, /purge).
	AdminToken = header.AdminToken

	// VerifyKey is the header used by the keystore /verify endpoint.
	VerifyKey = header.VerifyKey
)

// Tracing headers — W3C Trace Context and custom fleet tracing.
const (
	// TraceParent is the W3C trace-context propagation header.
	// See https://www.w3.org/TR/trace-context/#traceparent-header
	TraceParent = "Traceparent"

	// TraceState carries vendor-specific trace state alongside TraceParent.
	TraceState = "Tracestate"

	// Baggage carries arbitrary key=value pairs for distributed context.
	Baggage = "Baggage"
)

// Standard headers referenced by fleet middleware — kept here so
// callers don't need to remember the canonical casing.
const (
	ContentType   = "Content-Type"
	Authorization = "Authorization"
	UserAgent     = "User-Agent"
	CacheControl  = "Cache-Control"
	Origin        = "Origin"

	// CORS response headers.
	AccessControlAllowOrigin      = "Access-Control-Allow-Origin"
	AccessControlAllowMethods     = "Access-Control-Allow-Methods"
	AccessControlAllowHeaders     = "Access-Control-Allow-Headers"
	AccessControlExposeHeaders    = "Access-Control-Expose-Headers"
	AccessControlMaxAge           = "Access-Control-Max-Age"
	AccessControlAllowCredentials = "Access-Control-Allow-Credentials"
	AccessControlRequestMethod    = "Access-Control-Request-Method"
	AccessControlRequestHeaders   = "Access-Control-Request-Headers"
)

// ContentTypes are common MIME type values for Content-Type headers.
const (
	ContentTypeJSON            = "application/json"
	ContentTypeJSONCharsetUTF8 = "application/json; charset=utf-8"
	ContentTypePlainText       = "text/plain"
	ContentTypeFormEncoded     = "application/x-www-form-urlencoded"
	ContentTypeMultipart       = "multipart/form-data"
)
